apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: webapps
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "pods", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: webapps 
subjects:
- kind: ServiceAccount  # Note the dash (-) here
  name: jenkins
  namespace: webapps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: jenkins
    namespace: webapps
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: jenkins
    namespace: webapps
[cloudshell-user@ip-10-130-77-127 ~]$ cat secret.yaml 
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: jenkins
---

# kubectl describe secret -n webapps and take token 
